"""add crm entry resume code fields

Revision ID: 003bf90ae4aa
Revises: 504a75629aa9
Create Date: 2026-08-20 13:42:51.425825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003bf90ae4aa'
down_revision: Union[str, Sequence[str], None] = '504a75629aa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_entries', sa.Column('resume_code_hash', sa.String(length=64), nullable=True))
    op.add_column('crm_entries', sa.Column('resume_code_expires_at', sa.DateTime(), nullable=True))
    op.add_column('crm_entries', sa.Column('resume_code_attempts', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_entries', 'resume_code_attempts')
    op.drop_column('crm_entries', 'resume_code_expires_at')
    op.drop_column('crm_entries', 'resume_code_hash')
    # ### end Alembic commands ###
