"""add status_note to documents

Revision ID: 0282cb4167e5
Revises: de30f2c70997
Create Date: 2026-08-21 10:29:31.493869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0282cb4167e5'
down_revision: Union[str, Sequence[str], None] = 'de30f2c70997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('status_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status_note')
    # ### end Alembic commands ###
