"""add adyen payment settings columns

Revision ID: 06f80aeaf2f9
Revises: 80795a11c55a
Create Date: 2026-09-20 14:48:30.295910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06f80aeaf2f9'
down_revision: Union[str, Sequence[str], None] = '80795a11c55a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('adyen_api_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('adyen_client_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('adyen_merchant_account', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('adyen_hmac_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('adyen_environment', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'adyen_environment')
    op.drop_column('app_settings', 'adyen_hmac_key')
    op.drop_column('app_settings', 'adyen_merchant_account')
    op.drop_column('app_settings', 'adyen_client_key')
    op.drop_column('app_settings', 'adyen_api_key')
    # ### end Alembic commands ###
