"""add comment and served to order items

Revision ID: 1efd769f472c
Revises: d9feed93def7
Create Date: 2026-08-20 06:19:44.078045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1efd769f472c'
down_revision: Union[str, Sequence[str], None] = 'd9feed93def7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('comment', sa.String(length=255), nullable=True))
    op.add_column('order_items', sa.Column('served', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'served')
    op.drop_column('order_items', 'comment')
    # ### end Alembic commands ###
