"""add facebook and x oauth settings

Revision ID: 2e88ae50e73a
Revises: cf3a04994268
Create Date: 2026-08-22 11:43:05.518660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e88ae50e73a'
down_revision: Union[str, Sequence[str], None] = 'cf3a04994268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('facebook_oauth_client_id', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('facebook_oauth_client_secret', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('x_oauth_client_id', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('x_oauth_client_secret', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'x_oauth_client_secret')
    op.drop_column('app_settings', 'x_oauth_client_id')
    op.drop_column('app_settings', 'facebook_oauth_client_secret')
    op.drop_column('app_settings', 'facebook_oauth_client_id')
    # ### end Alembic commands ###
