"""add chat system prompt field to app settings

Revision ID: 3a3288c665c7
Revises: 64334945b22f
Create Date: 2026-08-21 03:04:47.464038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a3288c665c7'
down_revision: Union[str, Sequence[str], None] = '64334945b22f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('chat_system_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'chat_system_prompt')
    # ### end Alembic commands ###
