"""add map provider fields to app settings

Revision ID: 420a58a502e6
Revises: 003bf90ae4aa
Create Date: 2026-08-21 01:57:38.213378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '420a58a502e6'
down_revision: Union[str, Sequence[str], None] = '003bf90ae4aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('map_provider', sa.String(length=32), nullable=True))
    op.add_column('app_settings', sa.Column('google_maps_api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'google_maps_api_key')
    op.drop_column('app_settings', 'map_provider')
    # ### end Alembic commands ###
