"""add attachment_url to crm_entries

Revision ID: 4954780463a3
Revises: 7698e6cd5b1a
Create Date: 2026-08-08 10:34:17.718740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4954780463a3'
down_revision: Union[str, Sequence[str], None] = '7698e6cd5b1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_entries', sa.Column('attachment_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_entries', 'attachment_url')
    # ### end Alembic commands ###
