"""add email and sms notification provider fields

Revision ID: 504a75629aa9
Revises: 87f3741c695b
Create Date: 2026-08-20 13:28:44.912936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '504a75629aa9'
down_revision: Union[str, Sequence[str], None] = '87f3741c695b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('email_provider', sa.String(length=32), nullable=True))
    op.add_column('app_settings', sa.Column('mailgun_api_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('mailgun_domain', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('mailgun_from_address', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('sms_provider', sa.String(length=32), nullable=True))
    op.add_column('app_settings', sa.Column('twilio_account_sid', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('twilio_auth_token', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('twilio_from_number', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'twilio_from_number')
    op.drop_column('app_settings', 'twilio_auth_token')
    op.drop_column('app_settings', 'twilio_account_sid')
    op.drop_column('app_settings', 'sms_provider')
    op.drop_column('app_settings', 'mailgun_from_address')
    op.drop_column('app_settings', 'mailgun_domain')
    op.drop_column('app_settings', 'mailgun_api_key')
    op.drop_column('app_settings', 'email_provider')
    # ### end Alembic commands ###
