"""add business profile fields to app settings

Revision ID: 64334945b22f
Revises: 420a58a502e6
Create Date: 2026-08-21 02:17:39.401311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64334945b22f'
down_revision: Union[str, Sequence[str], None] = '420a58a502e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('business_name', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('business_description', sa.Text(), nullable=True))
    op.add_column('app_settings', sa.Column('business_type', sa.String(length=100), nullable=True))
    op.add_column('app_settings', sa.Column('business_email', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('business_phone', sa.String(length=64), nullable=True))
    op.add_column('app_settings', sa.Column('business_street_address', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('business_locality', sa.String(length=120), nullable=True))
    op.add_column('app_settings', sa.Column('business_region', sa.String(length=120), nullable=True))
    op.add_column('app_settings', sa.Column('business_postal_code', sa.String(length=32), nullable=True))
    op.add_column('app_settings', sa.Column('business_country', sa.String(length=120), nullable=True))
    op.add_column('app_settings', sa.Column('business_url', sa.String(length=500), nullable=True))
    op.add_column('app_settings', sa.Column('business_logo_url', sa.String(length=500), nullable=True))
    op.add_column('app_settings', sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('app_settings', sa.Column('business_social_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'business_social_links')
    op.drop_column('app_settings', 'business_hours')
    op.drop_column('app_settings', 'business_logo_url')
    op.drop_column('app_settings', 'business_url')
    op.drop_column('app_settings', 'business_country')
    op.drop_column('app_settings', 'business_postal_code')
    op.drop_column('app_settings', 'business_region')
    op.drop_column('app_settings', 'business_locality')
    op.drop_column('app_settings', 'business_street_address')
    op.drop_column('app_settings', 'business_phone')
    op.drop_column('app_settings', 'business_email')
    op.drop_column('app_settings', 'business_type')
    op.drop_column('app_settings', 'business_description')
    op.drop_column('app_settings', 'business_name')
    # ### end Alembic commands ###
