"""add wants_human to crm_entries

Revision ID: 65235cfb36c2
Revises: 7faca505a1f6
Create Date: 2026-08-20 02:30:09.993767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65235cfb36c2'
down_revision: Union[str, Sequence[str], None] = '7faca505a1f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_entries', sa.Column('wants_human', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_entries', 'wants_human')
    # ### end Alembic commands ###
