"""add app_settings table

Revision ID: 70a5f463ad14
Revises: 0b8942aec6a6
Create Date: 2026-08-04 01:28:18.779038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a5f463ad14'
down_revision: Union[str, Sequence[str], None] = '0b8942aec6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_provider', sa.String(length=32), nullable=True),
    sa.Column('chat_model', sa.String(length=200), nullable=True),
    sa.Column('vision_provider', sa.String(length=32), nullable=True),
    sa.Column('vision_model', sa.String(length=200), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_settings')
    # ### end Alembic commands ###
