"""add_turnstile_settings

Revision ID: 7695f87eea5a
Revises: 9b1d4e7a2c60
Create Date: 2026-09-09 14:20:59.168754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7695f87eea5a'
down_revision: Union[str, Sequence[str], None] = '9b1d4e7a2c60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('turnstile_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('app_settings', sa.Column('turnstile_site_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('turnstile_secret_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'turnstile_secret_key')
    op.drop_column('app_settings', 'turnstile_site_key')
    op.drop_column('app_settings', 'turnstile_enabled')
    # ### end Alembic commands ###
