"""add user_email to chat_sessions

Revision ID: 7698e6cd5b1a
Revises: e7968375fa9e
Create Date: 2026-08-08 09:44:35.764446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7698e6cd5b1a'
down_revision: Union[str, Sequence[str], None] = 'e7968375fa9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('user_email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'user_email')
    # ### end Alembic commands ###
