"""add inventory (Product stock/low-stock/variable-price, StockItem)

Revision ID: 80795a11c55a
Revises: d6f3bd31644c
Create Date: 2026-09-10 11:37:24.633265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80795a11c55a'
down_revision: Union[str, Sequence[str], None] = 'd6f3bd31644c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('variable_price', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'variable_price')
    op.drop_column('products', 'low_stock_threshold')
    op.drop_column('products', 'stock_quantity')
    op.drop_table('stock_items')
    # ### end Alembic commands ###
