"""add intent field options and intent schema form template

Revision ID: 8681175b6f0a
Revises: 8eb4b0753fd1
Create Date: 2026-09-22 13:23:02.296443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8681175b6f0a'
down_revision: Union[str, Sequence[str], None] = '8eb4b0753fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intent_fields', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('intent_schemas', sa.Column('form_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intent_schemas', 'form_template')
    op.drop_column('intent_fields', 'options')
    # ### end Alembic commands ###
