"""add payment gate fields to app_settings and orders

Revision ID: 87f3741c695b
Revises: 1efd769f472c
Create Date: 2026-08-20 12:59:32.939527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87f3741c695b'
down_revision: Union[str, Sequence[str], None] = '1efd769f472c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('payment_provider', sa.String(length=32), nullable=True))
    op.add_column('app_settings', sa.Column('stripe_secret_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('stripe_publishable_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('stripe_webhook_secret', sa.String(length=255), nullable=True))
    op.add_column('orders', sa.Column('payment_status', sa.String(length=16), server_default='unpaid', nullable=False))
    op.add_column('orders', sa.Column('payment_provider', sa.String(length=32), nullable=True))
    op.add_column('orders', sa.Column('payment_reference', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_reference')
    op.drop_column('orders', 'payment_provider')
    op.drop_column('orders', 'payment_status')
    op.drop_column('app_settings', 'stripe_webhook_secret')
    op.drop_column('app_settings', 'stripe_publishable_key')
    op.drop_column('app_settings', 'stripe_secret_key')
    op.drop_column('app_settings', 'payment_provider')
    # ### end Alembic commands ###
