"""add marketing sync settings columns

Revision ID: 8eb4b0753fd1
Revises: 06f80aeaf2f9
Create Date: 2026-09-21 00:23:25.205402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eb4b0753fd1'
down_revision: Union[str, Sequence[str], None] = '06f80aeaf2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('marketing_provider', sa.String(length=32), nullable=True))
    op.add_column('app_settings', sa.Column('mailchimp_api_key', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('mailchimp_audience_id', sa.String(length=64), nullable=True))
    op.add_column('app_settings', sa.Column('hubspot_access_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'hubspot_access_token')
    op.drop_column('app_settings', 'mailchimp_audience_id')
    op.drop_column('app_settings', 'mailchimp_api_key')
    op.drop_column('app_settings', 'marketing_provider')
    # ### end Alembic commands ###
