"""add oauth support: nullable password, oauth_provider, google oauth settings

Revision ID: 9001e608154d
Revises: 0282cb4167e5
Create Date: 2026-08-22 03:33:47.970407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9001e608154d'
down_revision: Union[str, Sequence[str], None] = '0282cb4167e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('google_oauth_client_id', sa.String(length=255), nullable=True))
    op.add_column('app_settings', sa.Column('google_oauth_client_secret', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('oauth_provider', sa.String(length=32), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'oauth_provider')
    op.drop_column('app_settings', 'google_oauth_client_secret')
    op.drop_column('app_settings', 'google_oauth_client_id')
    # ### end Alembic commands ###
