"""add email_verified to users

Revision ID: cf3a04994268
Revises: 9001e608154d
Create Date: 2026-08-22 11:29:59.611674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3a04994268'
down_revision: Union[str, Sequence[str], None] = '9001e608154d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

    # Data backfill (hand-added, not autogenerated) — every user row that
    # already exists as of this migration was created by seed.py (an
    # admin-provisioned, trusted path) since this app has no public
    # signup yet; mark them verified rather than leaving them at the
    # column's own cautious `false` default, which would otherwise make
    # apis/oauth.py's reclaim logic wipe out a real seeded account's
    # password the first time its email is used to sign in with Google.
    op.execute("UPDATE users SET email_verified = true")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
