"""add shipping fields to orders and app_settings

Revision ID: d6f3bd31644c
Revises: 7695f87eea5a
Create Date: 2026-09-10 07:44:05.653654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6f3bd31644c'
down_revision: Union[str, Sequence[str], None] = '7695f87eea5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('shipping_allowed_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('shipping_region', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_region')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('app_settings', 'shipping_allowed_regions')
    # ### end Alembic commands ###
