"""add is_company_material to documents

Revision ID: de30f2c70997
Revises: 85fa02b2424e
Create Date: 2026-08-21 04:10:00.335390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de30f2c70997'
down_revision: Union[str, Sequence[str], None] = '85fa02b2424e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('is_company_material', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'is_company_material')
    # ### end Alembic commands ###
