"""add category and status to crm_entries

Revision ID: e7968375fa9e
Revises: 43fe48dd8bda
Create Date: 2026-08-07 15:01:55.554377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7968375fa9e'
down_revision: Union[str, Sequence[str], None] = '43fe48dd8bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_entries', sa.Column('category', sa.String(length=32), nullable=True))
    op.add_column('crm_entries', sa.Column('status', sa.String(length=16), server_default='new', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_entries', 'status')
    op.drop_column('crm_entries', 'category')
    # ### end Alembic commands ###
