"""add contact_name, contact_phone, analysis_notes to crm_entries

Revision ID: fd073dfac6fd
Revises: 4954780463a3
Create Date: 2026-08-08 11:00:59.964308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd073dfac6fd'
down_revision: Union[str, Sequence[str], None] = '4954780463a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crm_entries', sa.Column('contact_name', sa.String(length=255), nullable=True))
    op.add_column('crm_entries', sa.Column('contact_phone', sa.String(length=64), nullable=True))
    op.add_column('crm_entries', sa.Column('analysis_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crm_entries', 'analysis_notes')
    op.drop_column('crm_entries', 'contact_phone')
    op.drop_column('crm_entries', 'contact_name')
    # ### end Alembic commands ###
